import {
  Apple,
  Baby,
  Backpack,
  BadgeDollarSign,
  Banknote,
  Bed,
  Beef,
  Beer,
  Bell,
  Bike,
  Bitcoin,
  Book,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Cake,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartLine,
  CircleDollarSign,
  CirclePoundSterling,
  Cloud,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Croissant,
  Dog,
  DollarSign,
  DoorOpen,
  Droplets,
  Dumbbell,
  Egg,
  Euro,
  FileText,
  Film,
  Flame,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  Hourglass,
  IceCream,
  Key,
  Landmark,
  Laptop,
  Lightbulb,
  Luggage,
  MapPin,
  Mic,
  Milk,
  Monitor,
  Music,
  Newspaper,
  Package,
  Palette,
  PartyPopper,
  PenLine,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlusCircle,
  Receipt,
  Repeat,
  Rocket,
  Salad,
  Scale,
  School,
  Scissors,
  Send,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Stethoscope,
  Tag,
  Ticket,
  Train,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Vault,
  Wallet,
  Wallet2,
  WalletCards,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  tag: Tag,
  wallet: Wallet,
  "wallet-2": Wallet2,
  "shopping-cart": ShoppingCart,
  "shopping-basket": ShoppingBasket,
  utensils: Utensils,
  car: Car,
  zap: Zap,
  "gamepad-2": Gamepad2,
  "heart-pulse": HeartPulse,
  heart: Heart,
  "shopping-bag": ShoppingBag,
  home: Home,
  housing: Home,
  briefcase: Briefcase,
  laptop: Laptop,
  monitor: Monitor,
  "trending-up": TrendingUp,
  "chart-line": ChartLine,
  "plus-circle": PlusCircle,
  coffee: Coffee,
  plane: Plane,
  gift: Gift,
  film: Film,
  book: Book,
  "book-open": BookOpen,
  dog: Dog,
  cat: Cat,
  baby: Baby,
  scissors: Scissors,
  wifi: Wifi,
  phone: Phone,
  dumbbell: Dumbbell,
  pill: Pill,
  stethoscope: Stethoscope,
  beer: Beer,
  wine: Wine,
  bus: Bus,
  train: Train,
  truck: Truck,
  ship: Ship,
  bike: Bike,
  fuel: Fuel,
  shirt: Shirt,
  sparkles: Sparkles,
  banknote: Banknote,
  "circle-dollar-sign": CircleDollarSign,
  "circle-pound-sterling": CirclePoundSterling,
  "credit-card": CreditCard,
  landmark: Landmark,
  "building-2": Building2,
  building: Building,
  "piggy-bank": PiggyBank,
  coins: Coins,
  smartphone: Smartphone,
  "wallet-cards": WalletCards,
  vault: Vault,
  "hand-coins": HandCoins,
  "hand-heart": HandHeart,
  euro: Euro,
  "dollar-sign": DollarSign,
  "badge-dollar-sign": BadgeDollarSign,
  bitcoin: Bitcoin,
  percent: Percent,
  scale: Scale,
  hourglass: Hourglass,
  users: Users,
  send: Send,
  shield: Shield,
  "shield-check": ShieldCheck,
  umbrella: Umbrella,
  repeat: Repeat,
  calendar: Calendar,
  bell: Bell,
  cloud: Cloud,
  music: Music,
  headphones: Headphones,
  tv: Tv,
  mic: Mic,
  ticket: Ticket,
  "party-popper": PartyPopper,
  hotel: Hotel,
  "map-pin": MapPin,
  luggage: Luggage,
  globe: Globe,
  rocket: Rocket,
  receipt: Receipt,
  "file-text": FileText,
  package: Package,
  pizza: Pizza,
  apple: Apple,
  salad: Salad,
  "ice-cream": IceCream,
  cake: Cake,
  cookie: Cookie,
  croissant: Croissant,
  beef: Beef,
  egg: Egg,
  milk: Milk,
  store: Store,
  key: Key,
  "door-open": DoorOpen,
  droplets: Droplets,
  flame: Flame,
  lightbulb: Lightbulb,
  bed: Bed,
  wrench: Wrench,
  hammer: Hammer,
  "tree-pine": TreePine,
  "flower-2": Flower2,
  palette: Palette,
  camera: Camera,
  watch: Watch,
  glasses: Glasses,
  gem: Gem,
  trophy: Trophy,
  backpack: Backpack,
  school: School,
  "graduation-cap": GraduationCap,
  "pen-line": PenLine,
  newspaper: Newspaper,
};

export type IconGroup = {
  label: string;
  icons: readonly string[];
};

export const CATEGORY_ICON_GROUPS: IconGroup[] = [
  {
    label: "General",
    icons: ["tag", "plus-circle", "gift", "package", "sparkles", "gem", "trophy", "rocket"],
  },
  {
    label: "Food & Drink",
    icons: [
      "utensils",
      "coffee",
      "pizza",
      "apple",
      "salad",
      "ice-cream",
      "cake",
      "cookie",
      "croissant",
      "beef",
      "egg",
      "milk",
      "beer",
      "wine",
    ],
  },
  {
    label: "Shopping",
    icons: ["shopping-cart", "shopping-basket", "shopping-bag", "store", "shirt"],
  },
  {
    label: "Transport & Travel",
    icons: [
      "car",
      "bus",
      "train",
      "truck",
      "ship",
      "bike",
      "plane",
      "fuel",
      "hotel",
      "map-pin",
      "luggage",
      "globe",
    ],
  },
  {
    label: "Home & Utilities",
    icons: [
      "home",
      "key",
      "door-open",
      "bed",
      "zap",
      "droplets",
      "flame",
      "lightbulb",
      "wifi",
      "phone",
      "cloud",
      "wrench",
      "hammer",
      "tree-pine",
      "flower-2",
    ],
  },
  {
    label: "Entertainment",
    icons: [
      "gamepad-2",
      "film",
      "music",
      "headphones",
      "tv",
      "mic",
      "ticket",
      "party-popper",
      "camera",
    ],
  },
  {
    label: "Health & Fitness",
    icons: ["heart-pulse", "stethoscope", "pill", "heart", "hand-heart", "dumbbell"],
  },
  {
    label: "Personal Care",
    icons: ["scissors", "palette", "glasses", "watch"],
  },
  {
    label: "Family & Pets",
    icons: ["dog", "cat", "baby"],
  },
  {
    label: "Education & Work",
    icons: [
      "book",
      "book-open",
      "backpack",
      "school",
      "graduation-cap",
      "pen-line",
      "newspaper",
      "briefcase",
      "laptop",
      "monitor",
    ],
  },
  {
    label: "Bills & Finance",
    icons: [
      "receipt",
      "file-text",
      "percent",
      "banknote",
      "badge-dollar-sign",
      "chart-line",
      "trending-up",
    ],
  },
  {
    label: "Insurance & Subscriptions",
    icons: ["calendar", "repeat", "bell", "shield", "shield-check", "umbrella"],
  },
];

export const ACCOUNT_ICON_GROUPS: IconGroup[] = [
  {
    label: "Wallets & Cards",
    icons: ["wallet", "wallet-2", "wallet-cards", "credit-card", "smartphone"],
  },
  {
    label: "Cash & Currency",
    icons: [
      "banknote",
      "coins",
      "hand-coins",
      "circle-dollar-sign",
      "dollar-sign",
      "euro",
      "circle-pound-sterling",
      "bitcoin",
      "percent",
    ],
  },
  {
    label: "Banks & Institutions",
    icons: ["landmark", "building-2", "building", "store", "home"],
  },
  {
    label: "Savings & Vaults",
    icons: ["piggy-bank", "vault", "shield-check", "hourglass", "gift"],
  },
  {
    label: "Investments",
    icons: ["chart-line", "trending-up", "gem", "rocket", "globe"],
  },
  {
    label: "Business & Joint",
    icons: ["users", "briefcase", "scale", "send"],
  },
];

/** @deprecated use CATEGORY_ICON_GROUPS */
export const CATEGORY_ICONS = CATEGORY_ICON_GROUPS.flatMap((group) => group.icons);

/** @deprecated use ACCOUNT_ICON_GROUPS */
export const ACCOUNT_ICONS = ACCOUNT_ICON_GROUPS.flatMap((group) => group.icons);

export function getLucideIcon(name: string, fallback: LucideIcon = Tag): LucideIcon {
  return ICON_MAP[name] ?? fallback;
}
