import {
  Baby,
  Banknote,
  Beer,
  Book,
  Briefcase,
  Building,
  Building2,
  Bus,
  Car,
  CircleDollarSign,
  Coffee,
  Coins,
  CreditCard,
  Dog,
  DollarSign,
  Dumbbell,
  Euro,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  HandCoins,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  PlusCircle,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Tag,
  Train,
  TrendingUp,
  Utensils,
  Vault,
  Wallet,
  WalletCards,
  Wifi,
  Wine,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  tag: Tag,
  wallet: Wallet,
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  car: Car,
  zap: Zap,
  "gamepad-2": Gamepad2,
  "heart-pulse": HeartPulse,
  "shopping-bag": ShoppingBag,
  home: Home,
  housing: Home,
  briefcase: Briefcase,
  laptop: Laptop,
  "trending-up": TrendingUp,
  "plus-circle": PlusCircle,
  coffee: Coffee,
  plane: Plane,
  gift: Gift,
  film: Film,
  book: Book,
  dog: Dog,
  baby: Baby,
  scissors: Scissors,
  wifi: Wifi,
  phone: Phone,
  dumbbell: Dumbbell,
  pill: Pill,
  beer: Beer,
  wine: Wine,
  bus: Bus,
  train: Train,
  fuel: Fuel,
  shirt: Shirt,
  sparkles: Sparkles,
  banknote: Banknote,
  "circle-dollar-sign": CircleDollarSign,
  "credit-card": CreditCard,
  landmark: Landmark,
  "building-2": Building2,
  "piggy-bank": PiggyBank,
  coins: Coins,
  smartphone: Smartphone,
  "wallet-cards": WalletCards,
  vault: Vault,
  "hand-coins": HandCoins,
  euro: Euro,
  "dollar-sign": DollarSign,
  building: Building,
};

export const CATEGORY_ICONS = [
  "tag",
  "shopping-cart",
  "utensils",
  "coffee",
  "car",
  "bus",
  "train",
  "plane",
  "fuel",
  "zap",
  "wifi",
  "phone",
  "gamepad-2",
  "film",
  "heart-pulse",
  "pill",
  "dumbbell",
  "shopping-bag",
  "shirt",
  "gift",
  "home",
  "dog",
  "baby",
  "book",
  "scissors",
  "beer",
  "wine",
  "briefcase",
  "laptop",
  "trending-up",
  "plus-circle",
  "banknote",
  "sparkles",
] as const;

export const ACCOUNT_ICONS = [
  "wallet",
  "credit-card",
  "banknote",
  "landmark",
  "building-2",
  "building",
  "piggy-bank",
  "coins",
  "hand-coins",
  "circle-dollar-sign",
  "dollar-sign",
  "euro",
  "smartphone",
  "wallet-cards",
  "vault",
] as const;

export function getLucideIcon(name: string, fallback: LucideIcon = Tag): LucideIcon {
  return ICON_MAP[name] ?? fallback;
}
